# Site settings
title: Zyleon's Backyard
email: itsurin.syu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Where there's a backyard, there always be a cat.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://noelyz.github.io" # the base hostname & protocol for your site
twitter_username: Zyleon
github_username:  NoElyz

# Build settings
markdown: kramdown
